[manager]
show_hidden = true
ratio = [2, 2, 5]

[plugin]
prepend_previewers = [
    { name = "*.csv", run = "bat" },
    { name = "*.md", run = "bat" },
    { mime = "text/*", run = "bat" },
    { mime = "*/xml", run = "bat" },
    { mime = "*/cs", run = "bat" },
    { mime = "*/javascript", run = "bat" },
    { mime = "*/scala", run = "bat" },
    { mime = "*/sbt", run = "bat" },
    { mime = "*/java", run = "bat" },
    { mime = "*/typescript", run = "bat" },
    { mime = "*/svelte", run = "bat" },
    { mime = "*/html", run = "bat" },
    { mime = "*/rust", run = "bat" },
    { mime = "*/json", run = "bat" },
    { mime = "*/toml", run = "bat" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
